### ISSUE TITLE
Setup of Vocola completely confusing

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/unimacro#23]
1.  there is no discussion of what the folders mean.

What is the user directtory and what is kept there?

What is the grammars directory?  Isn't the grammars what I use in C:\Users\Doug\OneDrive\doug\dication_toolbox\p3voice\vocola?  

What is the Vocola directory?  Why do i have to seelect it?  is is the source code for vocola?  Does the user really need to navigate to C:\Users\Doug\AppData\Roaming\Python\Python39\site-packages\?  Because nobody is used to navigating to AppData to do anything.

if my vocola user directory is C:\Users\Doug\OneDrive\doug\dication_toolbox\p3voice\vocola 
why did the install program create a folder  "C:\Users\Doug\.natlink\VocolaGrammars"?
 
If the vocola (or unimacro) source directories are required at runtime, why not write a python function AND a script (using flit)  like "vocala_source_directory" and "unimacro_source_directory"?  Why do we even need this info at config time?

**Comment by dougransom** [comment]
Here is my natlink ini. To me there should be one (or maybe zero if there is a natlink default user directory) setting for a folder: the folder where my customizations live.
C:\Users\Doug\OneDrive\doug\dication_toolbox\p3voice\vocola







`[directories]
vocoladirectory = C:\Users\Doug\AppData\Roaming\Python\Python39\site-packages\vocola2
vocolagrammarsdirectory = C:\Users\Doug\.natlink\VocolaGrammars

[userenglish-directories]

[userspanish-directories]

[settings]
log_level = DEBUG
load_on_startup = True
load_on_begin_utterance = False
load_on_mic_on = True
load_on_user_changed = True

[vocola]
vocolauserdirectory = C:\Users\Doug\OneDrive\doug\dication_toolbox\p3voice\vocola

`

**Comment by drmfinlay** [comment]
Hello Doug,

These are good points.  I too have found the new configuration of Natlink, and related projects, somewhat confusing.  Your posts are from a few months back. Are these issues still present?

**Comment by dougransom** [comment]
to be improved somewhat in next release.  and expect a new config gui as well.

**Comment by drmfinlay** [comment]
All right then.  :+1:

**Comment by quintijn** [comment]
We stick to this, except I added prefixes "natlink_userdir", which should be converted to "natlink_settingsdir", and ~ for home directory (C:\Users\Gebruiker\ on my computer.

Vocoladirectory is in sitepackages, and holds "_vocola_main.py", which is the controlling grammar of vocola.
vocolagrammarsdirectory holds the by vocola generated python grammar files. This directory should be local.

vocolauserdirectory holds the vocola command files (.vcl files).

(part of natlink.ini file):
[directories]
vocoladirectory = vocola2
vocolagrammarsdirectory = natlink_userdir\vocolagrammars

[vocola]
vocolauserdirectory = ~\Documents\vocola_qh
vocolatakeslanguages = True
vocolatakesunimacroactions = True
