### ISSUE TITLE
Visual Clue of When Unimacro is loaded and what version.

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/unimacro#31]
I would like to know when unimacro is loading and what version  as reported by the importlib module:

`>>> from importlib.metadata import version
>>> version("unimacro")
'4.1.2'`

Be careful not to load the version from __init__, I think that is problematic for a  couple reasons (one is the version number can be specified in pyproject.toml at a later time and this would break.).

Maybe if the full path were reported, and it was clear where  vocola stops and  unimacro starts?

loading module _control from c:\users\doug\...

```
loadAllFiles: C:\Users\doug\OneDrive\doug\VocolaGrammars, force: True
compile_Vocola, inputFileOrFolder: "C:\Users\doug\OneDrive\doug\VocolaGrammars"
loading module: _vocola_vcl
loading module: __init__
loading module: _control
loading module: _folders
Traceback (most recent call last):
  File "C:\Users\doug\AppData\Local\Programs\Python\Python310-32\lib\site-packages\natlinkcore\loader.py", line 305, in load_or_reload_module
```

**Comment by quintijn** [comment]
Unimacro is loaded by loading grammars, first _control.py and thereafter grammars that are in the unimacrogrammarsdirectory
