### ISSUE TITLE
edit spokenforms fails on first use

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/unimacro#4]
This appears in the log on 'edit spokenforms" speech:

> ---try to find spokenforms.ini file in old version (UserDirectory) or sample_ini directory
> no valid sample "zyx_spokenforms.ini" file found in one of 1 sample directories:
> |['c:\\users\\doug\\onedrive\\family\\doug\\work in progress\\voice projects\\unimacro\\sample_ini']|
> editSpokenForms: no valid spokenforms inifile for language "zyx" available
> 

I have not yet been able to determine a workaround.

**Comment by quintijn** [comment]
'zyx' means in unimacro a module cannot find the current language. I changed a few things there today. Could you please retry?

**Comment by dougransom** [comment]
---try to find spokenforms.ini file in old version (UserDirectory) or sample_ini directory
no valid sample "zyx_spokenforms.ini" file found in one of 1 sample directories:
|['c:\\users\\doug\\onedrive\\family\\doug\\work in progress\\voice projects\\unimacro\\sample_ini']|
editSpokenForms: no valid spokenforms inifile for language "zyx" available
---try to find spokenforms.ini file in old version (UserDirectory) or sample_ini directory
no valid sample "zyx_spokenforms.ini" file found in one of 1 sample directories:
|['c:\\users\\doug\\onedrive\\family\\doug\\work in progress\\voice projects\\unimacro\\sample_ini']|
editSpokenForms: no valid spokenforms inifile for language "zyx" available

**Comment by quintijn** [comment]
Solved by getting the language setting correct with natlinkstatus (natlink part)
