### ISSUE TITLE
Can't get "Show Folders" to work.

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/unimacro#5]
If i speak "show folders" i get this.

 

>  openFileDefault: C:\Users\Doug\AppData\Local\Temp\zyx___folders_help.txt (type: <class 'str'>, mode: edit, openWith: None)
> result of UnimacroBringUp: None
> could not open C:\Users\Doug\AppData\Local\Temp\zyx___folders_help.txt (mode: edit, openWith: None)
> delayed bringup does not work: AppBringUp "notepad
> 
> 
> 
> 
> 
> [bringup notepad++] c:\users\doug\appdata\local\temp\zyx___folders_help.txt","notepad
> 
> 
> 
> 
> 
> [bringup notepad++] ""C:\Users\Doug\AppData\Local\Temp\zyx___folders_help.txt"""
> deactivate _clickbyvoice

Also, it doesn't seem to matter what program i specify for .txt files.  Here is part of actions.ini, it should use notepad.

```
[bringup edit]
ini = notepad++
py = notepad++
pyw = notepad++
txt = notepad


 


[bringup notepad++]
name = notepad++ 
path = C:\ProgramFiles\notepad++
```

"Edit Grammar Folders" seems to work ok.

**Comment by quintijn** [comment]
OK, seems to be ok after language issue was solved...
