### ISSUE TITLE
Undetected Dragon Language can cause confusion

### ISSUE THREAD

**Issue by dougransom** [dictation-toolbox/unimacro#6]
if natlink doesn't detect the dragon language, and a new user glosses over the natlink log, they can get quite confused.  

In a future release, if the language isn't determined, maybe have fallback language in an ini file, and bail with instructions if there is no language detected or fallback set.

**Comment by quintijn** [comment]
Maybe even better, throw an error, and refuse to do any more work...

**Comment by quintijn** [comment]
More or less solved. I think all English "dialects" now target to "enx". 

If scripts are run outside the natlink environment (started by dragon with natlink.pyd as compatibility module), language = "tst" is returned, for testing purposes.
